### ISSUE TITLE
question about "build_LFR_features"

### ISSUE THREAD

**Issue by luweishuang** [kaituoxu/SpeechTransformer#15]
i found any feature the kaldi performed will pass function "build_LFR_features", is it has any special function? what's means by "stacking frames and skipping frames"?

**Comment by kaituoxu** [comment]
This function will generate Low Frame Rate (LFR) features.  Actually, LFR features is generated by stacking and skipping FBank features or other features (like MFCC).

Paper "THE SPEECHTRANSFORMER FOR LARGE-SCALE MANDARIN CHINESE SPEECH RECOGNITION" (https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8682586) provides an example, and actually I follow this paper to implement LFR features.
