### ISSUE TITLE
我想用训练好的模型推断自己录制好的语音，请问该怎么操作呢

### ISSUE THREAD

**Issue by chenpe32cp** [kaituoxu/SpeechTransformer#19]

**Comment by kaituoxu** [comment]
Stage 0/1/5 in egs/aishell/run.sh provides example.

You also can simplify stage 0/1/5 to decode your audio by your model.

**Comment by chenpe32cp** [comment]
Thank you very much, I will try.


 
---原始邮件---
发件人: "Kaituo XU 许开拓"<notifications@github.com>
发送时间: 2019年5月27日(星期一) 晚上8:27
收件人: "kaituoxu/Speech-Transformer"<Speech-Transformer@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"ChenPeng"<chenpeng0538@qq.com>;
主题: Re: [kaituoxu/Speech-Transformer] 我想用训练好的模型推断自己录制好的语音，请问该怎么操作呢 (#19)



Stage 0/1/5 in egs/aishell/run.sh provides example.
 
You also can simplify stage 0/1/5 to decode your audio by your model.

**Comment by feipeng-wang** [comment]
@kaituoxu Hi, I have the same question. you said stage 0/1/5 in run.sh shall guide the process of inference. But there is no stage 5 any more.  So is there any applicable example?  Thanks

**Comment by kaituoxu** [comment]
stage 0/1/4

**Comment by fresh382227905** [comment]
> s
Have you solved this problem and made it?

**Comment by feipeng-wang** [comment]
@kaituoxu ， Thanks! I walked through and figured out. For  fresh382227905 , Yes. As mentioned by the author.

**Comment by fresh382227905** [comment]
Hi, Have you ever tried to test your datasets  without transcript. It means that the datasets only have wav.
Thank you.
Looking forward to your reply.

**Comment by justStarG** [comment]
Where should I put my wav file? Can you should any finished shell script ?
