### ISSUE TITLE
bash.run.sh时

### ISSUE THREAD

**Issue by cst781** [kaituoxu/SpeechTransformer#22]
我在bash.run.sh的时候会报错，原因是run.sh第65行出现了一个没给的地址，请问一下应该怎么解决呢？

**Comment by kaituoxu** [comment]
Did you install Kaldi?

**Comment by cst781** [comment]
sorry, what you said is just my mistake.

**Comment by kaituoxu** [comment]
reopen if needed

**Comment by cst781** [comment]
why it still indicates it is not a directory after i install kaldi？

**Comment by kaituoxu** [comment]
Did you run `cd tools; make KALDI=/path/to/kaldi` said in README?

**Comment by cst781** [comment]
I solved it, but i met another unexpected problem, when i do the bash run.sh, I met this problem.
cp: cannot stat 'exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs16_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/ref.trn': No such file or directory
cp: cannot stat 'exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs16_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/hyp.trn': No such file or directory

**Comment by cst781** [comment]
我觉得上个问题是因为在stage 2 的时候会出现KeyError: u'BAC009S0041W0234'，这是什么原因呢？
