### ISSUE TITLE
support for multi-GPU

### ISSUE THREAD

**Issue by xdcesc** [kaituoxu/SpeechTransformer#23]
目前的脚本不支持多GPU，有没有哪位改成功的push一下？

**Comment by chenpe32cp** [comment]
我按照网上的方法加上DataPallel后，报Gather got an input of invalid size: got [10,35,9961], but expected [10,26,9961] 的错误，没找到啥问题，请问你的多GPU方案调试成功了吗？

**Comment by xdcesc** [comment]
> 我按照网上的方法加上DataPallel后，报Gather got an input of invalid size: got [10,35,9961], but expected [10,26,9961] 的错误，没找到啥问题，请问你的多GPU方案调试成功了吗？

没有成功，报错与你的相同

**Comment by junshipeng** [comment]
4 Traceback (most recent call last):
  5   File "/cephfs/group/cdg-wechat-u-cdg-wechat-asr/egs/Speech-Transformer/egs/aishell/../../src/bin/train.py", line 6, in <module>
  6     from data import AudioDataLoader, AudioDataset
  7   File "/cephfs/group/cdg-wechat-u-cdg-wechat-asr/egs/Speech-Transformer/src/data/data.py", line 99
  8     def __init__(self, *args, LFR_m=1, LFR_n=1, **kwargs):
  9                                   ^
楼主这个问题怎么解决的？

**Comment by fchest** [comment]
This script for multi-gpus is in https://github.com/fchest/Speech-Transformer-multi-GPUs. We change the Speech-Transformer into multi-GPUs.
