### ISSUE TITLE
遇到编码的问题

### ISSUE THREAD

**Issue by qycxzhangyi** [kaituoxu/SpeechTransformer#24]
在解码时(stage 4)，遇到如下问题：UnicodeEncodeError: 'ascii' codec can't encode character '\u751a' in position 6: ordinal not in range(128)。定位到代码，是decoder.py中print('hypo: ' + ''.join([char_list[int(x)] for x in hyp['yseq'][0, 1:]]))这一行代码出了问题。
网上的建议是设置utf-8编码，但是python3.6默认就是这个编码，很苦恼这个问题。

**Comment by kaituoxu** [comment]
试试python3.7?

**Comment by qycxzhangyi** [comment]
@kaituoxu 问题解决啦！

**Comment by zqs01** [comment]
You can refer to this link, I also solved this problem. https://blog.csdn.net/zhuqiushi123/article/details/89717020
