### ISSUE TITLE
ImportError: No module named torch

### ISSUE THREAD

**Issue by tsxce** [kaituoxu/SpeechTransformer#27]
您好，感谢您的开源，我在执行训练的时候前面0，1，2的步骤都训练。就是为什么在步骤3训练的时候好像采用的python版本会是python2？我把系统默认的python的软链接改到python 3.7又会报：Unknown option: --
usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
请问您的训练环境是怎么样的呢

**Comment by AChenQ** [comment]
您好，我现在也碰到这个问题了，请问您解决了吗

**Comment by AChenQ** [comment]
@xiechen0692 您好，我现在也碰到这个问题了，请问您解决了吗

**Comment by ghost** [comment]
Same here. I am sure I have torch installed in python3.
