### ISSUE TITLE
continue_from设置

### ISSUE THREAD

**Issue by xiaozhi1571** [kaituoxu/SpeechTransformer#29]
您好，我想在跑了2个epoch后保存的模型final.pth.tar上继续训练，continue_from应该如何设置呢？

**Comment by kaituoxu** [comment]
设为final.pth.tar的路径就行

**Comment by xiaozhi1571** [comment]
> final.pth.tar的路径就行

我设置成绝对路径会报错哎error: unrecognized arguments...还是要设置成相对谁的路径？
