### ISSUE TITLE
在解码中加入n-gram语言模型

### ISSUE THREAD

**Issue by zpppy** [kaituoxu/SpeechTransformer#7]
博主可以尝试在解码中加入n-gram语言模型，我试了下，有一定的效果。

**Comment by kobenaxie** [comment]
请问咋加语言模型？可以给了李子不

**Comment by kaituoxu** [comment]
欢迎添加引入n-gram的代码并提交pull requests。

**Comment by zpppy** [comment]
> 欢迎添加引入n-gram的代码并提交pull requests。

已申请合并。

**Comment by chenpe32cp** [comment]
请问您加入的语言模型，需要的lexicon.txt文件需要什么格式的，是如何得到的呢？

**Comment by chenpe32cp** [comment]
> > 欢迎添加引入n-gram的代码并提交pull requests。
> 
> 已申请合并。
请问您加入的语言模型，需要的lexicon.txt文件需要什么格式的，是如何得到的呢？
